apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
  namespace: {{ include "overlord.namespace" . }}
  labels:
    {{- include "overlord.commonLabels" . | nindent 4 }}
    app: {{ .Values.backend.app }}
spec:
  selector:
    app: {{ .Values.backend.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  type: {{ .Values.backend.service.type }}
