apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps-web-term-overlord-iscsi-pvc
  namespace: sandbox-overlord
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi
  resources:
    requests:
      storage: 1Gi
