apiVersion: v1
kind: PersistentVolume
metadata:
  name: apps-web-term-overlord-pv
spec:
  capacity:
    storage: 1024Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.0.0.3
    path: /srv/nfsroot/nfs-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps-web-term-overlord-pvc
  namespace: sandbox-overlord
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Mi
